### ISSUE TITLE
Please clarify license of exe files

### ISSUE THREAD

**Issue by joachimmetz** [jschicht/Mft2Csv#5]
The exe files seem to be generated by https://www.autoitscript.com/autoit3/docs/intro/compiler.htm which are covered by 
https://www.autoitscript.com/autoit3/docs/license.htm not by https://github.com/jschicht/Mft2Csv/blob/master/LICENSE.md

**Comment by joachimmetz** [comment]
Please add some information to the README that reflects this

**Comment by jschicht** [comment]
The referenced license states that compiled scripts are not covered by it. The license has anyways been changed to MIT, which should reflect the true intention.

**Comment by joachimmetz** [comment]
But that means the exe files are in the release https://github.com/jschicht/Mft2Csv/releases/download/v2.0.0.44/Mft2Csv_v2.0.0.44.zip are still subject to https://www.autoitscript.com/autoit3/docs/license.htm which is missing from the release package. With scripts au3 files are meant.

**Comment by jschicht** [comment]
The move of the exe's into release package was not done because of the licensing, but merely because it just makes more sense do split it like that. For the actual license, I may not fully understand the remaining issue. In the reference; https://www.autoitscript.com/autoit3/docs/license.htm it says in second ssection 
"The definition of SOFTWARE PRODUCT does not includes any files generated by the SOFTWARE PRODUCT, such as compiled script files in the form of standalone executables." 
Then under section 1. GRANT OF LICENSE it says; 
"You may sell for profit and freely distribute scripts and/or compiled scripts that were created with the SOFTWARE PRODUCT." 
My interpretation here is that compiled exe's as now found in the release package is thus not covered by that referenced license. Or have I missed something here?

**Comment by joachimmetz** [comment]
as far as I understand it, you need to create such a license for your executables, since you're re-distributing autoit code

**Comment by jschicht** [comment]
I tried getting more information at the forums about the need for that referenced license along with compiled scripts, but could not get any confirmation that it is needed, rather the contrary. I am closing this issue, and stay with my license interpretation and specifically this section "The definition of SOFTWARE PRODUCT does not includes any files generated by the SOFTWARE PRODUCT, such as compiled script files in the form of standalone executables.", in that it refers to the framework itself and not the output of it.

**Comment by joachimmetz** [comment]
From https://www.autoitscript.com/forum/topic/106706-distributing-and-using-autoit-to-exe-compiler-in-background/

```
If I understand it correctly, your only obligation is to make sure you distribute a copy of the EULA
with your product.
```
